[root@cp ~]# su - oracle
Last login: Wed Jul 11 12:22:03 +06 2018 on :1
Last failed login: Thu Jul 12 13:17:38 +06 2018 from 179.86.80.184 on ssh:notty
There was 1 failed login attempt since the last successful login.
[oracle@cp ~]$ 
[oracle@cp ~]$ 
[oracle@cp ~]$ 
[oracle@cp ~]$ 
[oracle@cp ~]$ vi .bash_history 
yum install tigervnc
exit
passwd oracle
xhost +
cd Database\
cd database
cd /database
cd /home/
ls
cd database/
./runInstaller
ping 8.8.8.8
./runInstaller
cd
. .bash_profile
./runInstaller
ping 8.8.8.8
su oracle
echo $DISPLAY
yum install tigervnc
exit
passwd oracle
xhost +
cd Database\
cd database
cd /database
cd /home/
ls
cd database/
./runInstaller
ping 8.8.8.8
./runInstaller
cd
. .bash_profile
./runInstaller
ping 8.8.8.8
su oracle
echo $DISPLAY
vi .bash_profile
exit
vi .bash_profile
. .bash_profile
exit
ping -c 1 centos7
echo $DISPLAY
export DISPLAY=:0.0
echo $DISPLAY
exit
sqlplus sys / as sysdba
sqlplus / as sysdba
exit



vi /u01/app/oracle/product/11.2.0.4/db_1/network/admin/tnsnames.ora
======================================================================

HTDB =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 203.95.220.5)(PORT = 1521))
    (CONNECT_DATA =
      (SERVICE_NAME = HTDB)
    )
  )

======================================================================

vi /u01/app/oracle/product/11.2.0.4/db_1/network/admin/sqlnet.ora

======================================================================
NAMES.DIRECTORY_PATH= (TNSNAMES, EZCONNECT)

ADR_BASE = /u01/app/oracle

======================================================================

vi /u01/app/oracle/product/11.2.0.4/db_1/network/admin/listener.ora


======================================================================
# Generated by Oracle configuration tools.

LISTENER =
  (DESCRIPTION_LIST =
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = TCP)(HOST = robi.4dlbangladesh.com)(PORT = 1521))
    )
  )

#ADR_BASE_LISTENER = /u01/app/oracle
======================================================================

